spring.application.name=temperature-processing
server.port=8082

# Habilita o console
spring.h2.console.enabled=true

# Define o caminho de acesso (opcional, o padrão já é /h2-console)
spring.h2.console.path=/h2-console

# Configuração básica da conexão (em memória)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=